from typing import Protocol

from app.modules.game_lists.domain.entities import GameList


class GameListRepository(Protocol):
    def create(self, *, user_id: int, name: str, description: str | None, is_public: bool = False) -> GameList: ...
    def list_by_user(self, user_id: int) -> list[GameList]: ...
    def get(self, *, user_id: int, list_id: int) -> GameList | None: ...
    def update(self, *, user_id: int, list_id: int, name: str, description: str | None) -> GameList: ...
    def delete(self, *, user_id: int, list_id: int) -> bool: ...
