from typing import Protocol

from app.modules.game_lists.domain.entities import GameList, ListedGame


class GameListRepository(Protocol):
    def create(self, *, user_id: int, name: str, description: str | None, is_public: bool = False) -> GameList: ...
    def list_by_user(self, user_id: int) -> list[GameList]: ...
    def get(self, *, user_id: int, list_id: int) -> GameList | None: ...
    def update(self, *, user_id: int, list_id: int, name: str, description: str | None) -> GameList: ...
    def delete(self, *, user_id: int, list_id: int) -> bool: ...


class GameListItemRepository(Protocol):
    def add(self, *, list_id: int, game_id: int) -> ListedGame: ...
    def remove(self, *, list_id: int, game_id: int) -> bool: ...
    def exists(self, *, list_id: int, game_id: int) -> bool: ...
    def count(self, list_id: int) -> int: ...
    def list_games(self, list_id: int) -> list[ListedGame]: ...
    def counts_by_list(self, list_ids: list[int]) -> dict[int, int]: ...
    def recent_covers(self, list_ids: list[int], *, limit: int = 5) -> dict[int, list[str]]: ...
    def list_ids_containing(self, *, list_ids: list[int], game_id: int) -> set[int]: ...


class GameCatalog(Protocol):
    def ensure_game(self, external_id: str) -> int: ...
    def resolve_game_id(self, external_id: str) -> int | None: ...
