from datetime import datetime
from typing import Protocol

from app.modules.users.domain.entities import EmailVerificationToken, User


class UserRepository(Protocol):
    def get_by_username(self, username: str) -> User | None: ...
    def get_by_email(self, email: str) -> User | None: ...
    def get_by_id(self, user_id: int) -> User | None: ...
    def add(self, user: User) -> User: ...
    def mark_email_verified(self, user_id: int) -> None: ...


class EmailVerificationTokenRepository(Protocol):
    def add(self, user_id: int, token_hash: str, expires_at: datetime) -> EmailVerificationToken: ...
    def get_by_hash(self, token_hash: str) -> EmailVerificationToken | None: ...
    def mark_used(self, token_id: int) -> None: ...
