export const texts = {
  feedbackModal: {
    closeAriaLabel: 'Fechar modal',
  },
  auth: {
    googleButton: 'Continuar com Google',
    googleError: 'Não foi possível autenticar com o Google. Tente novamente.',
  },
  signUp: {
    successMessage: 'Conta criada com sucesso! Faça login para continuar.',
    errorMessage: 'Não foi possível criar a conta. Tente novamente.',
  },
  header: {
    navCatalog: 'Catálogo',
    logoutAriaLabel: 'Sair',
    searchPlaceholder: 'Buscar jogos...',
    searchClearAriaLabel: 'Limpar busca',
    searchToggleAriaLabel: 'Abrir busca',
    userMenu: {
      profile: 'Perfil',
      myLists: 'Minhas listas',
      myGames: 'Meus jogos',
      reviews: 'Reviews',
    },
  },
  search: {
    loading: 'Buscando...',
    noResults: 'Nenhum jogo encontrado.',
    error: 'Erro ao buscar jogos.',
    retry: 'Tentar novamente',
  },
  catalog: {
    heroTitle: 'Seu diário de jogos.',
    heroSubtitle: 'Descubra, avalie e comente os jogos que marcaram a sua jornada.',
    sectionTitle: 'Atividade Recente',
    counterLabel: 'jogos',
    emptyTitle: 'Nenhuma atividade ainda',
    emptyDescription: 'Adicione, finalize ou avalie um jogo para começar.',
    emptyAddAction: 'Adicionar',
    loadError: 'Não foi possível carregar sua coleção.',
    activityFilters: {
      added: 'Jogos adicionados',
      finished: 'Finalizados',
      reviews: 'Reviews',
    },
  },
  addGame: {
    modalTitle: 'Adicionar um jogo',
    searchPlaceholder: 'Buscar jogos...',
    successMessage: 'Jogo adicionado com sucesso!',
    errorMessage: 'Não foi possível adicionar o jogo. Tente novamente.',
  },
  myGames: {
    pageTitle: 'Meus jogos',
    emptyTitle: 'Nenhum jogo adicionado',
    emptyDescription: 'Adicione jogos à sua lista para vê-los aqui.',
    loadError: 'Não foi possível carregar seus jogos.',
    perPageLabel: 'Por página:',
    removeAriaLabel: 'Remover jogo',
    removeSuccessMessage: 'Jogo removido com sucesso!',
    removeErrorMessage: 'Não foi possível remover o jogo. Tente novamente.',
  },
  comingSoon: {
    title: 'Em breve',
    description: 'Esta funcionalidade ainda está sendo desenvolvida.',
  },
  gameDetails: {
    ratingRawgLabel: 'RAWG',
    ratingPlatformLabel: 'Plataforma',
    ratingPlatformComingSoon: 'Em breve',
    aboutTitle: 'Sobre',
    noDescription: 'Sem descrição disponível.',
    screenshotsTitle: 'Screenshots',
    noScreenshots: 'Sem screenshots disponíveis.',
    developersLabel: 'Desenvolvedora',
    platformsLabel: 'Plataformas',
    releaseDateLabel: 'Lançamento',
    loadError: 'Não foi possível carregar os detalhes deste jogo.',
    notFoundTitle: 'Jogo não encontrado',
    notFoundDescription: 'Não conseguimos localizar este jogo.',
    retry: 'Tentar novamente',
    addToWantToPlay: 'Quero jogar',
    addedToWantToPlay: 'Adicionado',
    addToWantToPlaySuccess: 'Jogo adicionado à sua lista!',
    addToWantToPlayError: 'Não foi possível adicionar o jogo. Tente novamente.',
    yourRatingLabel: 'Sua nota',
    rateSuccess: 'Nota registrada com sucesso!',
    rateError: 'Não foi possível registrar sua nota. Tente novamente.',
    ratingRemovedSuccess: 'Nota removida.',
    removeRatingError: 'Não foi possível remover sua nota. Tente novamente.',
  },
}
