export const texts = {
  feedbackModal: {
    closeAriaLabel: 'Fechar modal',
  },
  auth: {
    googleButton: 'Continuar com Google',
    googleError: 'Não foi possível autenticar com o Google. Tente novamente.',
  },
  signUp: {
    successMessage: 'Conta criada com sucesso! Faça login para continuar.',
    errorMessage: 'Não foi possível criar a conta. Tente novamente.',
  },
  header: {
    navCatalog: 'Catálogo',
    navProfile: 'Perfil',
    logoutAriaLabel: 'Sair',
    searchPlaceholder: 'Buscar jogos...',
    searchClearAriaLabel: 'Limpar busca',
    searchToggleAriaLabel: 'Abrir busca',
  },
  search: {
    loading: 'Buscando...',
    noResults: 'Nenhum jogo encontrado.',
    error: 'Erro ao buscar jogos.',
    retry: 'Tentar novamente',
  },
  catalog: {
    heroTitle: 'Seu diário de jogos.',
    heroSubtitle: 'Descubra, avalie e comente os jogos que marcaram a sua jornada.',
    sectionTitle: 'Atividade Recente',
    counterLabel: 'jogos',
    emptyTitle: 'Nenhuma atividade ainda',
    emptyDescription: 'Adicione, finalize ou avalie um jogo para começar.',
    emptyAddAction: 'Adicionar',
    loadError: 'Não foi possível carregar sua coleção.',
    activityFilters: {
      added: 'Jogos adicionados',
      finished: 'Finalizados',
      reviews: 'Reviews',
    },
  },
  comingSoon: {
    title: 'Em breve',
    description: 'Esta funcionalidade ainda está sendo desenvolvida.',
  },
  gameDetails: {
    ratingRawgLabel: 'RAWG',
    ratingPlatformLabel: 'Plataforma',
    ratingPlatformComingSoon: 'Em breve',
    aboutTitle: 'Sobre',
    noDescription: 'Sem descrição disponível.',
    screenshotsTitle: 'Screenshots',
    noScreenshots: 'Sem screenshots disponíveis.',
    developersLabel: 'Desenvolvedora',
    platformsLabel: 'Plataformas',
    releaseDateLabel: 'Lançamento',
    loadError: 'Não foi possível carregar os detalhes deste jogo.',
    notFoundTitle: 'Jogo não encontrado',
    notFoundDescription: 'Não conseguimos localizar este jogo.',
    retry: 'Tentar novamente',
    addToWantToPlay: 'Quero jogar',
  },
}
