from typing import Protocol

from app.modules.games.domain.entities import GameDetail, GameSearchResult, UserGame, UserGameStatus


class GameSearchProvider(Protocol):
    def search(self, query: str) -> list[GameSearchResult]: ...


class GameDetailProvider(Protocol):
    def get_by_id(self, game_id: str) -> GameDetail: ...


class GameRepository(Protocol):
    def find_by_id(self, game_id: str) -> GameDetail | None: ...
    def save(self, detail: GameDetail) -> None: ...


class UserGameRepository(Protocol):
    def add(self, *, user_id: int, game_id: int, status: UserGameStatus = UserGameStatus.want_to_play) -> UserGame: ...
    def remove(self, *, user_id: int, game_id: int) -> bool: ...
    def list_by_user(self, user_id: int, status: UserGameStatus | None = None) -> list[UserGame]: ...
    def exists(self, *, user_id: int, game_id: int) -> bool: ...
    def find_internal_game_id(self, external_id: str) -> int | None: ...
    def get(self, *, user_id: int, game_id: int) -> UserGame | None: ...
    def set_rating(self, *, user_id: int, game_id: int, rating: float) -> UserGame: ...
    def clear_rating(self, *, user_id: int, game_id: int) -> bool: ...
