from typing import Protocol

from app.modules.games.domain.entities import GameDetail, GameSearchResult, UserGame


class GameSearchProvider(Protocol):
    def search(self, query: str) -> list[GameSearchResult]: ...


class GameDetailProvider(Protocol):
    def get_by_id(self, game_id: str) -> GameDetail: ...


class GameRepository(Protocol):
    def find_by_id(self, game_id: str) -> GameDetail | None: ...
    def save(self, detail: GameDetail) -> None: ...


class UserGameRepository(Protocol):
    def add(self, *, user_id: int, game_id: int) -> UserGame: ...
    def remove(self, *, user_id: int, game_id: int) -> bool: ...
    def list_by_user(self, user_id: int) -> list[UserGame]: ...
    def exists(self, *, user_id: int, game_id: int) -> bool: ...
    def find_internal_game_id(self, external_id: str) -> int | None: ...
